lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
    user_id_claim: email
    api_platform:
        check_path: /api/login
        username_path: email
        password_path: password

